# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Status.create(title: 'Analysis')
Status.create(title: 'Closed')
Status.create(title: 'Development')
Status.create(title: 'For Prioritization')
Status.create(title: 'User Testing')
Status.create(title: 'Ready for Production')
Status.create(title: 'Open')
Status.create(title: 'Development queue')
Status.create(title: 'Analyst queue')
Status.create(title: 'On-Hold')
Status.create(title: 'Abap Development queue')
Status.create(title: 'Analyst Testing')
Status.create(title: 'Migrations')
Status.create(title: 'Design')
Status.create(title: 'Implementation')
Status.create(title: 'Discovery')

BusinessUnit.create(title: 'Automotive')
BusinessUnit.create(title: 'Electronics')
BusinessUnit.create(title: 'POWR-GARD')
BusinessUnit.create(title: 'Relay')
BusinessUnit.create(title: 'Shared Services')
BusinessUnit.create(title: 'Silicon')

Category.create(title: 'Administration')
Category.create(title: 'Audit')
Category.create(title: 'Enhancements')
Category.create(title: 'Landscape')
Category.create(title: 'Projects')
Category.create(title: 'PTO')
Category.create(title: 'Support')
Category.create(title: 'Training')

Plant.create(title: 'Cole Hersee')
Plant.create(title: 'Dongguan')
Plant.create(title: 'HQ')
Plant.create(title: 'Lithuania')
Plant.create(title: 'Muzquiz')
Plant.create(title: 'Philippines')
Plant.create(title: 'Piedras Negras')
Plant.create(title: 'Saskatoon')
Plant.create(title: 'Suzhou')
Plant.create(title: 'Wuxi')

Area.create(title: 'Abap')
Area.create(title: 'Basis')
Area.create(title: 'Business Center')
Area.create(title: 'BW')
Area.create(title: 'EDI')
Area.create(title: 'Engineering')
Area.create(title: 'FICO')
Area.create(title: 'Global Labeling')
Area.create(title: 'IT Operations')
Area.create(title: 'Littelfuse.com')
Area.create(title: 'Manufacturing')
Area.create(title: 'Marketing')
Area.create(title: 'Operations')
Area.create(title: 'SCM')
Area.create(title: 'SD')
Area.create(title: 'Server')
Area.create(title: 'Sugar CRM')


